# Generated by Django 3.0.8 on 2020-08-10 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoices',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('idSalesInvoices', models.IntegerField(primary_key=True, serialize=False)),
                ('dateCreateInvoice', models.DateTimeField()),
                ('idAccountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesCart',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('idSalesCart', models.IntegerField(primary_key=True, serialize=False)),
                ('quantityOfProductsSold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('PriceOfProductsSold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('createdTime', models.DateTimeField()),
                ('updatedTime', models.DateTimeField()),
                ('productCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.Product')),
                ('salesInvoicesCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesManager.SalesInvoices')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
