# Generated by Django 3.0.8 on 2020-08-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('idCategories', models.IntegerField(primary_key=True, serialize=False)),
                ('nameCategories', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('idProduct', models.IntegerField(primary_key=True, serialize=False)),
                ('nameProduct', models.CharField(max_length=100)),
                ('expiredProduct', models.DateTimeField()),
                ('quantityProduct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categoriesCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.Categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
