# Generated by Django 3.0.8 on 2020-08-12 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('idPurchaseInvoice', models.IntegerField(primary_key=True, serialize=False)),
                ('dateCreatePurchaseInvoice', models.DateTimeField()),
                ('accountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceInput',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('idSourceInput', models.IntegerField(primary_key=True, serialize=False)),
                ('addressSourceInput', models.CharField(max_length=100)),
                ('emailSourceInput', models.CharField(max_length=45)),
                ('phoneSourceInput', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceDetails',
            fields=[
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantityOfPurchasedProducts', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('buyProductPrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('productCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.Product')),
                ('purchaseInvoiceCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseManagement.PurchaseInvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='sourceInputCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseManagement.SourceInput'),
        ),
    ]
